name: CD - Deploy StuCents Staging

on:
  push:
    branches:
      - new-developer

env:
  ACR_NAME: stucentsregistry
  IMAGE_NAME: stucents-app1
  IMAGE_TAG: staging
  RESOURCE_GROUP: stucents-rg
  CONTAINER_APP_NAME: stucentsapp1
  LOCATION: francecentral
  ACR_LOGIN_SERVER: stucentsregistry.azurecr.io
  TF_VAR_environment: staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: student_expense_tracker/infra

    - name: Terraform Plan
      run: terraform plan -var-file=${{ env.TF_VAR_environment }}.tfvars
      working-directory: student_expense_tracker/infra

    - name: Show Staging App URL
      run: terraform output -raw container_app_url
      working-directory: student_expense_tracker/infra

    - name: Azure ACR login using access token
      run: |
        az acr login --name $ACR_NAME --expose-token | jq -r '.accessToken' | \
        docker login $ACR_LOGIN_SERVER -u 00000000-0000-0000-0000-000000000000 --password-stdin

    - name: Build Docker image
      run: docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG .

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@0.11.2
      with:
        image-ref: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        format: table
        exit-code: 0
        ignore-unfixed: true

    - name: Push Docker image
      run: docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

    - name: Terraform Apply
      run: terraform apply -var-file=${{ env.TF_VAR_environment }}.tfvars -auto-approve
      working-directory: student_expense_tracker/infra